AllCops:
  TargetRubyVersion: 2.3

Lint/AssignmentInCondition:
  AllowSafeAssignment: true

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
