# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d268e828a6b7d070bee3027b77595a4f196090a42db97a534b52811ecf403490c4a5ea8b375a18551e4f71cc2fc7ee3f384ca3118bb88affcf3c747eb9983be3

test:
  secret_key_base: 25e931835b52559ed6ff9985acb0b3743f8e026700dd50ea5d1b7d8c38eb0ac82bd0c4abd4129606107c441e452e8330def16635e25aa7cf89b6fc39cfeecd29

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
